tasks:
  - name: "Init"
    init: |
      git clone https://github.com/vlang/v
      cd v
      make
    command: |
      # Symlink V (this resets every time)
      sudo ./v/v symlink
      # Install Clockwork (this needs to be done every time unfortunately)
      # We cd to ~ so that we do not delete an install.vsh that may already exist.
      cd ~
      v download -RD https://raw.githubusercontent.com/EmmaTheMartian/clockwork/refs/heads/main/scripts/install.vsh
      cd -
      # Install project dependencies
      clockwork deps
